/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.previred.desafio.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.previred.desafio.model.Periodos;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.util.Optional;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-10-26T00:07:05.808Z")


@Api(value = "api", description = "API REST para obtener las fechas faltantes desde el servicio GDD")
public interface ApiApi {

    Logger log = LoggerFactory.getLogger(ApiApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "consulta cuantos periodos faltan", nickname = "getPeriodosFaltantes", notes = "", response = Periodos.class, tags = {"getPeriodosFaltantes",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Ok", response = Periodos.class)})
    @RequestMapping(value = "/api",
            produces = {"application/json"},
            method = RequestMethod.GET)

    default ResponseEntity<Periodos> getPeriodosFaltantes() {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"fechaCreacion\" : \"2000-01-23\",  \"fechas\" : [ \"2000-01-23\", \"2000-01-23\" ], \"fechasFaltantes\" : [ \"2000-01-23\", \"2000-01-23\" ], \"id\" : 0,  \"fechaFin\" : \"2000-01-23\"}", Periodos.class), HttpStatus.OK);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ApiApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
