openapi: 3.0.0
info:
  description:  Implementación de Desafío Uno
  version: 1.0.0
  title: API periodos
servers:
  - url: http://localhost:8090/
components:
  schemas:
    Periodo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fechaCreacion:
          type: string
          format: date
        fechaFin:
          type: string
          format: date
        fechas:
          type: array
          items:
            type: string
            format: date
        fechasFaltantes:
          type: array
          items:
            type: string
            format: date
paths:
  /api:
    get:
      summary: Lista de periodos a procesados
      operationId: periodos
      responses:
          '200':
            description: Lista de periodos a procesados 
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Periodo'