/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.previred.periodos.swagger.codegen.api;

import com.previred.periodos.swagger.codegen.model.Periodo;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import javax.servlet.http.HttpServletRequest;
import java.util.Optional;

@Api(value = "api")
public interface ApiApi {

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Lista de periodos a procesar", nickname = "periodosAgregado", notes = "", response = Periodo.class, tags={ "periodosAgregado", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Periodo y lista de fechas", response = Periodo.class) })
    @GetMapping(value = "/api",
        produces = { "application/json" })
    default ResponseEntity<Periodo> periodosAgregado(@RequestParam String inicio, @RequestParam String fin) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
