// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package types

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Periodo defines model for Periodo.
type Periodo struct {
	FechaCreacion   *openapi_types.Date   `json:"fechaCreacion,omitempty"`
	FechaFin        *openapi_types.Date   `json:"fechaFin,omitempty"`
	Fechas          *[]openapi_types.Date `json:"fechas,omitempty"`
	FechasFaltantes *[]openapi_types.Date `json:"fechasFaltantes,omitempty"`
	Id              *int64                `json:"id,omitempty"`
}
