swagger: '2.0'
info:
  description: >-
   Prueba para desafío de implementación 
  version: 1.0.0
  title: API periodos perdidos
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: cesar.ogalde@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: '127.0.0.1:8181'
basePath: /periodos/perdidos
tags:
  - name: perdidos
    description: Lista de periodos a procesar con periodos perdidos
schemes:
  - http
paths:
  /api:
    get:
      tags:
        - perdidos
      summary: Lista de periodos a procesar con periodos perdidos
      operationId: perdidos
      produces:
        - application/json
      responses:
        '200':
          description: Periodo con perdidos y lista de fechas
          schema:
            $ref: '#/definitions/PeriodoPerdido'
definitions:
  PeriodoPerdido:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fechaCreacion:
        type: string
        format: date
      fechaFin:
        type: string
        format: date
      fechas:
        type: array
        items:
          type: string
          format: date
      fechasFaltantes:
        type: array
        items:
          type: string
          format: date
externalDocs:
  description: Especificación de swagger
  url: 'https://swagger.io/docs/specification/about/'
