/*
 * API periodos
 * Prueba para desafío de implementación 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mgonzalez@previred.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import desafiocuatro.periodos.swagger.codegen.model.Periodo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PeriodosApi
 */
@Ignore
public class PeriodosApiTest {

    private final PeriodosApi api = new PeriodosApi();

    
    /**
     * Lista de periodos a procesar
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void periodosTest() {
        Periodo response = api.periodos();

        // TODO: test validations
    }
    
}
