server.port: 8081
springfox.documentation.swagger.v2.path: /api-docs
server.servlet.context-path: /periodos-perdidos
spring.jackson.date-format: com.previred.periodosperdidos.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

generadorDeDatos.url: http://127.0.0.1:8080/periodos/api


