swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8081'
basePath: /
tags:
  - name: basic-error-controller
    description: Basic Error Controller
  - name: faltantes-controller
    description: Faltantes Controller
paths:
  /faltantes:
    get:
      tags:
        - faltantes-controller
      summary: faltantes
      operationId: faltantesUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OutputModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  OutputModel:
    type: object
    properties:
      id:
        type: integer
        format: int32
      fechaCreacion:
        type: string
        format: date
      fechaFin:
        type: string
        format: date
      fechas:
        type: array
        items:
          type: string
          format: date
      fechasFaltantes:
        type: array
        items:
          type: string
          format: date
    title: OutputModel

