/*
 * API periodos
 * Prueba para desafío de implementación 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mgonzalez@previred.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.pr3v1r3d.desafio1.client.model;

import java.util.Objects;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Periodo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-23T23:26:01.172-04:00")
public class GddResponse {

	private LocalDate fechaCreacion = null;
	private LocalDate fechaFin = null;
	private List<LocalDate> fechas = null;
	private Long id = null;

	public GddResponse fechaCreacion(LocalDate fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
		return this;
	}

	/**
	 * Get fechaCreacion
	 * @return fechaCreacion
	 **/
	public LocalDate getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(LocalDate fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public GddResponse fechaFin(LocalDate fechaFin) {
		this.fechaFin = fechaFin;
		return this;
	}

	/**
	 * Get fechaFin
	 * @return fechaFin
	 **/
	public LocalDate getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(LocalDate fechaFin) {
		this.fechaFin = fechaFin;
	}

	public GddResponse fechas(List<LocalDate> fechas) {
		this.fechas = fechas;
		return this;
	}

	public GddResponse addFechasItem(LocalDate fechasItem) {
		if (this.fechas == null) {
			this.fechas = new ArrayList<LocalDate>();
		}
		this.fechas.add(fechasItem);
		return this;
	}

	/**
	 * Get fechas
	 * @return fechas
	 **/
	public List<LocalDate> getFechas() {
		return fechas;
	}

	public void setFechas(List<LocalDate> fechas) {
		this.fechas = fechas;
	}

	public GddResponse id(Long id) {
		this.id = id;
		return this;
	}

	/**
	 * Get id
	 * @return id
	 **/
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GddResponse periodo = (GddResponse) o;
		return Objects.equals(this.fechaCreacion, periodo.fechaCreacion) &&
				Objects.equals(this.fechaFin, periodo.fechaFin) &&
				Objects.equals(this.fechas, periodo.fechas) &&
				Objects.equals(this.id, periodo.id);
	}

	@Override
	public int hashCode() {
		return Objects.hash(fechaCreacion, fechaFin, fechas, id);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Periodo {\n");

		sb.append("    fechaCreacion: ").append(toIndentedString(fechaCreacion)).append("\n");
		sb.append("    fechaFin: ").append(toIndentedString(fechaFin)).append("\n");
		sb.append("    fechas: ").append(toIndentedString(fechas)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

